### PR TITLE
Some changes from Will

### PR DESCRIPTION
**Pull request by will**
Do these 2 changes look correct @gregburek ?

### CODE REVIEW

**Comment by will** [comment]
Do the PX dynos spin down between each test? Asked differently: is there any fear of dyno cycling during a test?

**Comment by gregburek** [comment]
Changes look good. 

PX workers are run dynos so they should stay up for 24 hours. The individual tests at a certain client count are all part of a larger pgbench test. The dyno needs to keep running for the larger pgbench test. 

There is a risk that if the test+vacuum time is >24 hours the dynos will restart leaving an unfinished job. I have not yet seen this or tested it.

**Comment by will** [comment]
@gregburek there are 7 tests, so 6 hours would be 1.75 days.

I only went with 6 because I think you recommended that, should we go with a smaller amount of time?

**Comment by will** [comment]
Could also maybe drop the higher client count, these plans aren't supposed to have that many. Maybe go to 5 hours and only the first 4 (1, 10, 100, and 200 clients)? total test time would be 20 hours with 4 hours left over for the vacuuming?

**Comment by gregburek** [comment]
5 hours seems reasonable. Also, you could run the full test suite multiple
times for the absolute worst case.

**Pull request merged**
